Validator and errorhandling
anssi55/Epic-bulletin-board-backend-project pull request #5
Opened 2019-07-16 19:29 UTC by anssi55

In this branch validation and errorhandling was added to this app

2019-07-16 20:47 UTC, henrikra commented
Fix conflicts before review :D

2019-07-17 17:21 UTC, henrikra requested changes
Couple fixes and then it is ready 👍

2019-07-17 17:21 UTC, henrikra commented on app/app.ts
> +const cors = require('cors');
Hmm I guess this was changed to legacy style import by accident? 🤔

2019-07-17 17:21 UTC, henrikra commented on app/app.ts
> +    this.app.use(errorMiddleware);
Inject `errorMiddleware` also instead of `App` having hard dependency on it :)

2019-07-17 17:21 UTC, henrikra commented on app/dic.ts
> +  return createConnection().then(async connection => {
`async` not needed

2019-07-17 17:21 UTC, henrikra commented on app/dic.ts
> +export default container;
Is this `export` needed?

2019-07-17 17:21 UTC, henrikra commented on app/dto/CreatePost.ts
> +  public pinned!: string;
Validator is checking for boolean but TypeScript type is string? :D Please check other validation classes also if there are other cases likes this :)

2019-07-17 17:21 UTC, henrikra commented on app/exceptions/NotFoundException.ts
> +  constructor(type: String, id: String) {
Always use lowercase version of basic types `String` -> `string`

2019-07-17 17:21 UTC, henrikra commented on app/exceptions/HttpException.ts
> +  constructor(status: number, message: string) {
Check this short article https://dev.to/satansdeer/typescript-constructor-shorthand-3ibd on how to make this file quite a bit shorter ;)

2019-07-17 17:21 UTC, henrikra commented on app/exceptions/CouldNotSaveException.ts
> +class CouldNotSaveException extends HttpException {
I like this approach that you said you found in the article. I usually tend to use https://github.com/hapijs/boom to create errors because if you would start new project then you have to create this boilerplate again. But you choose which way you want to go 👍 Both are good options

2019-07-17 17:21 UTC, henrikra commented on app/middleware/validation.middleware.ts
> +          errors.map((error: ValidationError) => Object.values(error.constraints)).join(', ');
I think type for `error` here is inferred so there is no need to explicitly type it

2019-07-17 17:21 UTC, henrikra commented on app/routes/authRouter.ts
> +import { Router, Request, Response, NextFunction, response } from 'express';
Is `response` needed?

2019-07-17 17:21 UTC, henrikra commented on app/routes/categoryRouter.ts
> +export default categoriesRouter.router;
Move this service also to DI container 👍

2019-07-17 17:21 UTC, henrikra commented on app/routes/index.ts
> +    //.get(this.postsRouter.getAll)
Remove commented code which is not needed 👍

2019-07-17 17:21 UTC, henrikra commented on app/routes/index.ts
> +    this.router.use('/api/v1/categories', categoriesRouter);
This dependency should be injected

2019-07-17 17:21 UTC, henrikra commented on package.json
> +    "start": "ts-node build/app/startapp.js"
You should have same casing to your files in this case camelCased 👍

2019-07-17 17:21 UTC, henrikra commented on package.json
> -    "@types/cors": "^2.8.5",
Hmm why this was removed? 🤔

2019-07-18 09:13 UTC, anssi55 commented on app/exceptions/CouldNotSaveException.ts
> +class CouldNotSaveException extends HttpException {
I will look into this👍

2019-07-18 10:10 UTC, henrikra commented
Approved! 👍  You can now move to CircleCI stuff!

2019-07-18 10:13 UTC, merged